#PROBLEM1
A is 3x3, B is 3x3 => product matrix AB is 3x3. 

To obtain the entry in row 1, column 1 of AB, multiply the first row in A by the first column in B, and add.
-1 x 0 + 2 x 0 + 3 x 2 = 6

To obtain the entry in row 1, column 2 of AB, multiply the first row in A by the first column in B, and add.
-1 x 2 + 2 x 2 + 3 x 9 = 29

To obtain the entry in row 1, column 3 of AB, multiply the first row in A by the first column in B, and add.
-1 x 1 + 2 x -8 + 3 x -1 = -20

We proceed the same way to obtain AB. The product AB is [[6, 29, -20], [12, 52, 38], [-18, -51, -48]]
      

In [6]:
#PROBLEM2
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

print(np.matmul(a_ndarray, b_ndarray))
print(np.dot(a_ndarray, b_ndarray))
print(a_ndarray @ b_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [7]:
#PROBLEM3
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

AB_00 = a_ndarray[0, 0] * b_ndarray[0, 0] + a_ndarray[0, 1] * b_ndarray[1, 0] + a_ndarray[0, 2] * b_ndarray[2, 0]
print(AB_00)

6


In [39]:
#PROBLEM4
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

def calculate_matrix(a, b):
  product = []
  ele = 0
  for i in range(len(a)):
    for j in range(len(b[0])):
      for k in range(len(b)):
        ele += a[i][k] * b[k][j]
      product.append(ele)
      ele = 0
  product = np.array(product)
  product = product.reshape(len(a), len(b[0]))
  return product

result = calculate_matrix(a_ndarray, b_ndarray)
print(result)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [40]:
#PROBLEM5
import numpy as np

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

def calculate_matrix(a, b):
  if not ((len(a[0])) == len(b)):
    print("Invalid input")
    return
  product = []
  ele = 0
  for i in range(len(a)):
    for j in range(len(b[0])):
      for k in range(len(b)):
        ele += a[i][k] * b[k][j]
      product.append(ele)
      ele = 0
  product = np.array(product)
  product = product.reshape(len(a), len(b[0]))
  return product

result = calculate_matrix(d_ndarray, e_ndarray)
print(result)

Invalid input
None


In [41]:
#PROBLEM6
import numpy as np

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
d_ndarray = np.transpose(d_ndarray)
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

def calculate_matrix(a, b):
  if not ((len(a[0])) == len(b)):
    print("Invalid input")
    return
  product = []
  ele = 0
  for i in range(len(a)):
    for j in range(len(b[0])):
      for k in range(len(b)):
        ele += a[i][k] * b[k][j]
      product.append(ele)
      ele = 0
  product = np.array(product)
  product = product.reshape(len(a), len(b[0]))
  return product

result = calculate_matrix(d_ndarray, e_ndarray)
print(result)

[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]
