In [33]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris

#PROBLEM1
StandardScaler

DataFrame

LinearRegression

KNeighborsClassifier

Timestamp

In [9]:
data = load_iris()
X = data.data[:10]
scaler = StandardScaler()

scaler = StandardScaler()
scaler.fit(X)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [10]:
print("Mean : {}".format(scaler.mean_)) 
print("Var : {}".format(scaler.var_)) 

Mean : [4.86 3.31 1.45 0.22]
Var : [0.0764 0.0849 0.0105 0.0056]


#PROBLEM2




> Instance variable:
1.   pandas.DataFrame.size
2.   pandas.DataFrame.index
3.   sklearn.preprocessing.StandardScaler.mean_
4.   sklearn.preprocessing.StandardScaler.var_


> Method:
1.   numpy.hstack
2.   numpy.concatenate
3.   sklearn.linear_model.LinearRegression.fit
4.   sklearn.linear_model.LinearRegression.predict







In [11]:
X_std = scaler.transform(X)
X_std

array([[ 0.86828953,  0.65207831, -0.48795004, -0.26726124],
       [ 0.14471492, -1.06391725, -0.48795004, -0.26726124],
       [-0.57885968, -0.37751902, -1.46385011, -0.26726124],
       [-0.94064699, -0.72071813,  0.48795004, -0.26726124],
       [ 0.50650222,  0.99527742, -0.48795004, -0.26726124],
       [ 1.95365143,  2.02487476,  2.43975018,  2.40535118],
       [-0.94064699,  0.3088792 , -0.48795004,  1.06904497],
       [ 0.50650222,  0.3088792 ,  0.48795004, -0.26726124],
       [-1.66422159, -1.40711636, -0.48795004, -0.26726124],
       [ 0.14471492, -0.72071813,  0.48795004, -1.60356745]])

In [34]:
#PROBLEM3
class ScratchStandardScaler():
    """
    標準化のためのクラス
    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ = np.mean(X, axis=0)
        self.var_ = np.var(X, axis=0)

    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量
        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_scaled = (X - self.mean_)/np.sqrt(self.var_)
        return X_scaled

In [35]:
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("Mean : {}".format(scratch_scaler.mean_))
print("Var : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

Mean : [4.86 3.31 1.45 0.22]
Var : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


In [49]:
#PROBLEM4
class OperationClass():
    """
    説明用の簡単なクラス
    Parameters
    ----------
    value : float or int
        初期値
    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
      if type(value) == int or type(value) == float:
        self.value = value
        print("初期値{}が設定されました".format(self.value))
      else:
        raise Exception("Invalid")
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
    def sub(self, value2):
        self.value -= value2
    def mul(self, value2):
        self.value *= value2
    def div(self, value2):
        self.value /= value2

example = OperationClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))
example.sub(4)
print("value : {}".format(example.value))
example.mul(10)
print("value : {}".format(example.value))
example.div(20)
print("value : {}".format(example.value))

初期値5が設定されました
value : 5
value : 8
value : 4
value : 40
value : 2.0
